#include "../includes/defs.hpp"

#include <cstring>
#include <iostream>
#include <fstream>

void Yaml(int argc, char *argv[])
{
    if (argc > 1 && strcmp(argv[1], "-cfg") == 0)
    {
        defs::osf YamlCfg("chefs_choice.yml");

        YamlCfg << "# This file has been auto-generated by Bake"
                << std::endl
                << "# It contains a lot of preferences that you can customise"
                << std::endl
                << "# You can also change the name of the target Bakefile"
                << std::endl
                << std::endl
                << "# If you want to regenerate this file: run bake with '-cfg' argument"
                << std::endl
                << "# Remember: Bake is currently under development, so not all features might work!"
                << std::endl
                << std::endl;

        YamlCfg.close();
    }
}
