#include "../../includes/import.hpp"
#include "../../includes/defs.hpp"

using namespace defs;

void Yaml(int argc, char *argv[])
{
    using namespace std;

    if (argc > 1 && strcmp(argv[1], "-cfg") == 0)
    {
        defs::osf YamlCfg("chefs_choice.yml");

        YamlCfg << "# THIS FILE IS A PLACEHOLDER CURRENTLY AND HAS NO FUNCTION!"
                << endl
                << endl;

        YamlCfg << "# This file has been auto-generated by Bake"
                << endl
                << "# It contains preferences that you can customise"
                << endl
                << "# You can also change the name of the target Bakefile"
                << endl
                << endl
                << "# If you want to regenerate this file: run bake with '-cfg' argument"
                << endl
                << "# Remember: Bake is currently under development, so not all features might work!"
                << endl
                << endl
                << "# If you don't want to use the YAML file anymore, change it to false"
                << endl
                << "# You can also set 'BuildFromYaml' mode to 'True'"
                << endl
                << "# Setting BuildFromYaml to true will make it so that Bake bakes everything from here"
                << endl
                << endl
                << "Yaml: False"
                << endl
                << "BuildFromYaml: False"
                << endl
                << endl
                << "# This is the function where you can specify build commands"
                << endl
                << "[BuildFromYaml]"
                << endl
                << "  - del_file: 'rm -rf foo bar'"
                << endl
                << "  - spameggs: 'spam eggs'"
                << endl
                << endl
                << "# And this is the normal function if you are also using Bakefile"
                << endl
                << "# Also, the 'default' value means the default stored in the program, so:"
                << endl
                << "# Bakefile as name without an extension"
                << endl
                << endl
                << "# Remember to change 'default' to desired value"
                << endl
                << "# And you need to specify a drive letter (i.e. X:\\) if you're on Windows"
                << endl
                << "[Yaml]"
                << endl
                << "  - BakeFileName: default"
                << endl
                << "  - BakeFileExtension: default"
                << endl
                << "  - BakeFilePath: default"
                << endl;

        YamlCfg.close();

        exit(0);
    }
}
